### PR TITLE
Add tests for boss.api.slack module

### PR DESCRIPTION
**Pull request by gigkokman**
Adding tests for boss api slack

### CODE REVIEW

**Comment by kabirbaidhya** [comment]
Hi @gigkokman thanks for contributing. 
Travis is not showing any status yet on this PR, I've enabled it now can you make some minor changes and push a commit? And we can check this in the CI.

**Comment by gigkokman** [comment]
Look like it has issue about fabric.

**Comment by gigkokman** [comment]
> Fabric is a Python (2.5-2.7) library and command-line tool for streamlining the use of SSH for application deployment or systems administration tasks.

I think we can not use fabric with Python 3.

**Comment by kabirbaidhya** [comment]
@gigkokman Seems like not all of the fabric features are supported on python 3+, although their tests are passing here https://travis-ci.org/fabric/fabric. 

We will address this compatibility issues separately. 

However, if you see this file https://github.com/kabirbaidhya/boss/blob/master/boss/api/slack.py#L7 this `boss.api.slack` module isn't actually dependent on fabric.

Can you remove this [line](https://github.com/kabirbaidhya/boss/blob/master/boss/api/slack.py#L7):
```python
 from fabric.api import local, parallel
```

And remove the used `@parallel` decorator from this [line](https://github.com/kabirbaidhya/boss/blob/master/boss/api/slack.py#L32)

These were few of the things that need to be removed. I think tests should pass after this.

**Comment by gigkokman** [comment]
@kabirbaidhya In requirement, we use Fabric==1.13.2 [https://travis-ci.org/fabric/fabric/builds/289623892](url)  that compatible only Python 2+, while Fabric v2 will compatible with both Python 2+ and Python 3+

**Comment by kabirbaidhya** [comment]
@gigkokman I've pushed some changes in the `master` branch in the slack api https://github.com/kabirbaidhya/boss/commit/b53a8483bec0c998b4e829b91c34208601d5a262. I think this should fix the issue for now.

Can you pull the upstream `master` branch, and push it again? Then we can check the CI

**Comment by gigkokman** [comment]
Fabric is used in boss.util that is used in boss.config and all module use config module, so that I think it still is compatibility issue.

**Comment by kabirbaidhya** [comment]
LOL. Then I guess, there's no quick fix to this issue at the moment :smile: . I'll create a different branch for python3 support and will merge this PR in that for now. Later when we've found a work around will get this into master.

Anyway, thanks for your contribution :100: :+1:.

**Pull request merged**
